blog/urls.py
from django.contrib import admin
from django.urls import path
from django.http import HttpResponse
from . import views


urlpatterns = [
    path('', views.post_list, name='post_list'),
    #path('(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    path('<int:pk>/', views.post_detail, name='post_detail'), 
]

hellomeltingpod/urls.py
from django.contrib import admin
from django.urls import path , include

from django.http import HttpResponse
from django.conf import settings
from django.conf.urls.static import static


def hello(request):
	return HttpResponse('''
		<h1>Hello!.. askDjango</h1>
	''')
urlpatterns = [
    path('admin/', admin.site.urls),
    #path('blog/', include('blog.urls', namespace='blog')),
    path('blog/', include(('blog.urls', 'blog'), namespace ='blog')),

    path('', hello),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
        title = models.CharField(max_length=100)
        content = models.TextField()
        photo = models.ImageField()
        created_at = models.DateTimeField(auto_now_add=True)
        updated_at = models.DateTimeField(auto_now=True)

        def _str_(self):
                return self.title

class Comment(models.Model):
        post = models.ForeignKey(Post, on_delete=models.PROTECT)  #20190613 added some code by jpanda 'on_delete'
        message = models.TextField()

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from .models import Post


# Create your views here.
'''
def post_list(request):
	return render(request, 'blog/post_list.html')

'''


post_list = ListView.as_view(model=Post)
post_detail = DetailView.as_view(model=Post)

blog/templates/blog/base.html
<!doctype html>
<html>
<head>
<meta charset="utf8" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/flatly/bootstrap.min.css" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  
  <style>
	
  </style>
</head>

<body>

<nav class="navbar navbar-expand-sm bg-light">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="#">Link 1</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Link 2</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Link 3</a>
    </li>
  </ul>
</nav>
<br>
{% block content%}
{% endblock%}




</body>
</html>

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}

<div class="container">
	<div class="row">
		<div class = "col-sm-12">
			<table class="table table-hover table-bordered">
				<h1> {{post.title}}</h1>
				<p><img src="{{post.photo.url}}" /></p>
				{{post.content|linebreaks}}
				<hr/>
				<a href="{%url "blog:post_list" %}", class ="btn btn-primary"> To List </a>
			</table>
		</div>
	</div>
</div>



{%endblock%}

blog/templates/blog/post_list.html
{%extends "blog/base.html"%}

{%block content%}

<div class="container">
	<div class="row">
		<div class = "col-sm-12">
			<table class="table table-hover table-bordered">
				{% for post in post_list%}
					<tr>
						<td>
							<a href="{% url "blog:post_detail" post.pk %}">
								{{post.title}}
							</a>
						
						</td>
					</tr>
				{%endfor%}

			</table>
		</div>
	</div>
</div>
	




{% endblock%}